# Generated by Django 4.0.2 on 2022-02-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
